services:
  - type: web
    name: quantity-measurement-frontend
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist/quantity-measurement-app-frontend/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
